#????
server:
  port: 9003
#spring??
spring:
  #1.????
  application:
    name: FRS-Blog
  #2.??????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.194.211.199:3306/frscommunity?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: clg
    password: MYSQLzhu19981210.@
    dbcp2:
      initial-size: 3
      min-idle: 3
      max-idle: 15
      max-total: 30
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 42.194.211.199
    port: 6379
    password: Rxz129810.@EDIS
