#????
server:
  port: 9003
#spring??
spring:
  #1.????
  application:
    name: FRS-Blog
  #2.??????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.194.211.199:3306/frscommunity?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: clg
    password: MYSQLzhu19981210.@
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
      max-lifetime: 0
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 42.194.211.199
    port: 6379
    password: Rxz129810.@EDIS

#eruka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true #开启客户端 hystrix

management:
  endpoints:
    web:
      exposure:
        include: "*"   # * 在yaml 文件属于关键字，所以需要加引号
info:
  app.name: micro-service-cloud-provider-dept-hystrix
  company.name: c.biancheng.net
  build.aetifactId: @project.artifactId@
  build.version: @project.version@